### ISSUE TITLE
Regarding the comparison of PDP with GPS

### ISSUE THREAD

**Issue by h-fantastic** [wanxinjin/Pontryagin-Differentiable-Programming#1]
I'm very interested in the difference between PDP with GPS in your PDP paper. Therefore, can you share the GPS code? Appreciate your help.

**Comment by wanxinjin** [comment]
Hi there, thank you for your interest in our paper. 

Of course! I have added the "ControlTool" folder, under which all comparison methods (including a deterministic GPS implementation) are realized in this script: [ControlTool/ControlTools.py](https://github.com/wanxinjin/Pontryagin-Differentiable-Programming/blob/master/ControlTool/ControlTools.py). Please check them out!

The script of training a robot arm with GPS is in [Examples/OC/robotarm/obotarm_GPS.py](https://github.com/wanxinjin/Pontryagin-Differentiable-Programming/blob/master/Examples/OC/robotarm/robotarm_GPS.py). The script of training a cartpole with GPS is in [Examples/OC/cartpole/cartpole_GPS.py](https://github.com/wanxinjin/Pontryagin-Differentiable-Programming/blob/master/Examples/OC/cartpole/cartpole_GPS.py).

Thank you!

**Comment by h-fantastic** [comment]
It is very helpful to me. Thank you!
