### ISSUE TITLE
When does it converge?

### ISSUE THREAD

**Issue by nsk126** [wanxinjin/Pontryagin-Differentiable-Programming#2]
I tried running `cartpole_PDP.py` using whatever was available default but the simulation never ends even at an iteration of 5000 the loss goes down to as low as 1e-4. Is this intentional? Is a loss of 1e-4 not enough to converge?

Brief output @ ~5000 iterations in Trial 0
```
trial: 0 iter: 5064 loss: 0.00036640417384145395
trial: 0 iter: 5065 loss: 0.00036634601681496026
trial: 0 iter: 5066 loss: 0.00036628787185822957
trial: 0 iter: 5067 loss: 0.0003662297345094633
trial: 0 iter: 5068 loss: 0.00036617160847844795
trial: 0 iter: 5069 loss: 0.00036611349147638297
```

**Comment by wanxinjin** [comment]
Hi @nsk126 , thanks for the interests. Yes, it is the intentional. I have not set any criteria to stop the iteration process. You can set you your convergence criteria by checking 1) the norm of grad is small enough, or 2) max iteration count. Hope this helps.

**Comment by nsk126** [comment]
Thank you for clarifying. Sorry for the late reply. I will try to implement one of the ideas and see if the results are good.
